# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - local
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - local

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.3"

      - name: Test
        run: go test -v ./...

  go-release:
    if: startsWith(gitea.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.3"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        env:
          GITEA_TOKEN: ${{ secrets.REPOSITORY_PAT }}
        with:
          distribution: goreleaser
          version: ~> v2
          args: release --clean
